version: 2
updates:
- package-ecosystem: "gitsubmodule"
  directory: "/"
  target-branch: "master"
  schedule:
    interval: "daily"
- package-ecosystem: "gomod"
  directory: "/src/rabbitmq-service-broker"
  target-branch: "master"
  schedule:
    interval: "daily"
- package-ecosystem: "bundler"
  directory: "/"
  target-branch: "master"
  schedule:
    interval: "daily"
