source 'https://rubygems.org'

gem 'bosh_cli', '1.3262.26.0'
gem 'rake'
gem 'rabbitmq_http_api_client'
gem 'bosh-template'
gem 'httparty'
gem 'pry-byebug'
gem 'rspec','~> 3.3'
gem 'rspec-instafail'
gem 'capybara-webkit', '~> 1.11.0'
gem 'bunny'
gem 'mqtt'
gem 'stomp'
gem 'prof'
gem 'hula'
gem 'rspec-retry'
gem 'papertrail'
