source 'https://rubygems.org'

gem 'bosh-template'
gem 'bunny'
gem 'capybara-webkit', '~> 1.11.0'
gem 'httparty'
gem 'mqtt'
gem 'papertrail'
gem 'pry-byebug'
gem 'rabbitmq_http_api_client'
gem 'rake'
gem 'rspec', '~> 3.3'
gem 'rspec-instafail'
gem 'rspec-retry'
gem 'stomp'
