#!/usr/bin/env bash

set -e

[ -z "$DEBUG" ] || set -x

WORKSPACE="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../" && pwd)" #taken from https://github.com/cloudfoundry/bosh-lite/blob/master/bin/provision_cf#L7

BOSH_CMD=bosh

export BOSH_ENVIRONMENT="${1:-https://192.168.50.6:25555}"
export BOSH_NON_INTERACTIVE=false
export BOSH_CLIENT=admin
export BOSH_CLIENT_SECRET=admin
export BOSH_DEPLOYMENT=cf-rabbitmq-multitenant-broker
export BOSH_CA_CERT
BOSH_CA_CERT="$(boshgo int ~/deployments/vbox/creds.yml --path /director_ssl/ca)"

main() {
  local manifest
  manifest=$(interpolate-manifest-for-bosh-lite)

  upload_stemcell "$manifest"

  download_blobs
  update_src_dependencies

  create_dev_release && upload_dev_release
  upload_cf_rabbitmq_test_release

  deploy "$manifest"
  register_multitenant_broker
}

interpolate-manifest-for-bosh-lite() {
  local manifest
  manifest=$(mktemp)

  "$WORKSPACE/cf-rabbitmq-multitenant-broker-release/scripts/interpolate-manifest-for-bosh-lite" "$manifest"
}

upload_stemcell() {
  local manifest="$1"
  BOSH_LITE_STEMCELL_NAME="bosh-warden-boshlite-ubuntu-trusty-go_agent"
  BOSH_LITE_STEMCELL_VERSION="$(yq .stemcells[0].version "$manifest")"
  BOSH_LITE_STEMCELL_URL="https://bosh.io/d/stemcells/$BOSH_LITE_STEMCELL_NAME?v=$BOSH_LITE_STEMCELL_VERSION"

  $BOSH_CMD upload-stemcell "$BOSH_LITE_STEMCELL_URL" --name "$BOSH_LITE_STEMCELL_NAME" --version "$BOSH_LITE_STEMCELL_VERSION"
}

download_blobs() {
  $BOSH_CMD sync-blobs
}

update_src_dependencies() {
  git submodule update --init --recursive
}

create_dev_release() {
  $BOSH_CMD create-release --force
}

upload_dev_release() {
  $BOSH_CMD upload-release
}

upload_cf_rabbitmq_test_release() {
  (
    cd "$WORKSPACE"/cf-rabbitmq-test-release
    $BOSH_CMD create-release --force
    $BOSH_CMD upload-release
  )
}

update_cloud_config() {
  $BOSH_CMD update-cloud-config "$BOSH_CLOUD_CONFIG"
}

deploy() {
  $BOSH_CMD deploy --no-redact "$manifest"
}

register_multitenant_broker() {
  $BOSH_CMD run-errand broker-registrar
}

main
