#!/usr/bin/env bash

set -e

[ -z "$DEBUG" ] || set -x

WORKSPACE="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../" && pwd)" #taken from https://github.com/cloudfoundry/bosh-lite/blob/master/bin/provision_cf#L7
BOSH_LITE_URL="${1:-https://192.168.50.4:25555}"
CF_ROUTING_RELEASE_VERSION="0.152.0"
CF_ROUTING_RELEASE="cf-routing-release-${CF_ROUTING_RELEASE_VERSION}.tgz"
CF_ROUTING_RELEASE_URL="http://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=$CF_ROUTING_RELEASE_VERSION"
BOSH_CLOUD_CONFIG="manifests/lite-cloud-config.yml"

read -rep "BOSH manifest for the cf-rabbitmq deployment (default: $PWD/manifests/cf-rabbitmq-broker.yml): " BOSH_MANIFEST
BOSH_MANIFEST="${BOSH_MANIFEST:-$PWD/manifests/cf-rabbitmq-broker.yml}"

BOSH_LITE_STEMCELL_NAME="bosh-warden-boshlite-ubuntu-trusty-go_agent"
BOSH_LITE_STEMCELL_VERSION="$(yq .stemcells[0].version $BOSH_MANIFEST)"
BOSH_LITE_STEMCELL_URL="https://bosh.io/d/stemcells/$BOSH_LITE_STEMCELL_NAME?v=$BOSH_LITE_STEMCELL_VERSION"

BOSH_CMD=boshgo

export BOSH_ENVIRONMENT=$BOSH_LITE_URL
export BOSH_CA_CERT=$WORKSPACE/bosh-lite/ca/certs/ca.crt
export BOSH_NON_INTERACTIVE=true

main() {
  upload_stemcell

  download_blobs
  update_src_dependencies

  create_dev_release
  upload_dev_release
  upload_routing_release
  upload_cf_rabbitmq_test_release

  update_cloud_config
  deploy

  target_cf || cf_required
}

upload_stemcell() {
  stemcell_already_exists=$("$BOSH_CMD" --json stemcells | jq ".Tables[].Rows[] | select(.version == \""$BOSH_LITE_STEMCELL_VERSION"\")")

  if [ -z "$stemcell_already_exists" ];
  then
    $BOSH_CMD upload-stemcell "$BOSH_LITE_STEMCELL_URL"
  else
    echo "Stemcell $BOSH_LITE_STEMCELL_VERSION already present. Moving on."
  fi
}

download_blobs() {
  $BOSH_CMD sync-blobs
}

update_src_dependencies() {
  git submodule update --init --recursive
}

create_dev_release() {
  $BOSH_CMD create-release --force
}

upload_dev_release() {
  $BOSH_CMD upload-release
}

upload_routing_release() {
  (
    cd "$WORKSPACE"
    [ -f "$CF_ROUTING_RELEASE" ] || curl -L -o "$CF_ROUTING_RELEASE" "$CF_ROUTING_RELEASE_URL"
    $BOSH_CMD upload-release "$CF_ROUTING_RELEASE"
  )
}

upload_cf_rabbitmq_test_release() {
  (
    cd "$WORKSPACE"/cf-rabbitmq-test-release
    $BOSH_CMD create-release --force
    $BOSH_CMD upload-release
  )
}

update_cloud_config() {
  $BOSH_CMD update-cloud-config "$BOSH_CLOUD_CONFIG"
}

deploy() {
  $BOSH_CMD deploy --var=stemcell-version=${BOSH_LITE_STEMCELL_VERSION} --no-redact -d cf-rabbitmq-multitenant-broker "${BOSH_MANIFEST/#\~/$HOME}"
}

target_cf() {
  cf l -a api.bosh-lite.com -u admin -p admin --skip-ssl-validation
}

cf_required() {
  echo "Cloud Foundry v238+ must be deployed on this BOSH director, http://docs.cloudfoundry.org/deploying/boshlite/index.html"
  exit 1
}

main
