#!/usr/bin/env bash

set -e
set -u
set -o pipefail

: "${WORKSPACE:="$HOME/workspace"}"
: "${RELEASE_PATH:="$WORKSPACE/cf-rabbitmq-multitenant-broker-release"}"

[[ -z "${DEBUG:-""}" ]] || set -x

export BOSH_ENVIRONMENT=${BOSH_ENVIRONMENT:-"https://192.168.50.6:25555"}
export BOSH_CLIENT=${BOSH_CLIENT:-"admin"}
export BOSH_CLIENT_SECRET=${BOSH_CLIENT_SECRET:-"admin"}
export BOSH_CA_CERT
BOSH_CA_CERT=${BOSH_CA_CERT:-"$(boshgo int ~/deployments/vbox/creds.yml --path /director_ssl/ca)"}

BOSH_MANIFEST="${1:-$RELEASE_PATH/manifests/cf-rabbitmq-broker.yml}"

main() {
  local bosh_uuid
  bosh_uuid=$(get_local_bosh_lite_uuid)

  do_interpolate "$bosh_uuid"
}

get_local_bosh_lite_uuid() {
  bosh \
    environment --json | jq  -r .Tables[].Rows[].uuid
}

do_interpolate() {
  local bosh_uuid=${1:?"Expected BOSH UUID"}
  local new_manifest="$BOSH_MANIFEST"

  boshgo interpolate \
    --var-errs \
    --ops-file="$RELEASE_PATH/manifests/add-cf-rabbitmq.yml" \
    --ops-file="$RELEASE_PATH/manifests/change-vcap-password.yml" \
    --vars-file="$RELEASE_PATH/manifests/lite-vars-file.yml" \
    --var=director-uuid="$bosh_uuid" \
  "$RELEASE_PATH/manifests/cf-rabbitmq-broker-template.yml" \
  > "$new_manifest"

  echo "$new_manifest"
}

main "$@"
