#!/usr/bin/env bash

set -e
set -u
set -o pipefail

: "${WORKSPACE:="$HOME/workspace"}"
: "${RELEASE_REPO:="$WORKSPACE/cf-rabbitmq-multitenant-broker-release"}"

[[ -z "${DEBUG:-""}" ]] || set -x

export BOSH_ENVIRONMENT="https://192.168.50.6:25555"
export BOSH_CLIENT="admin"
export BOSH_CLIENT_SECRET="admin"
export BOSH_CA_CERT
BOSH_CA_CERT="$(boshgo int ~/deployments/vbox/creds.yml --path /director_ssl/ca)"

BOSH_MANIFEST="${1:-$RELEASE_REPO/manifests/cf-rabbitmq-broker.yml}"

main() {
  local bosh_uuid
  bosh_uuid=$(get_local_bosh_lite_uuid)

  do_interpolate "$bosh_uuid"
}

get_local_bosh_lite_uuid() {
  bosh \
    environment --json | jq  -r .Tables[].Rows[].uuid
}

do_interpolate() {
  local bosh_uuid=${1:?"Expexted bosh uuid"}
  local new_manifest="$BOSH_MANIFEST"

  boshgo interpolate \
    --var-errs \
    --ops-file="$RELEASE_REPO/manifests/add-cf-rabbitmq.yml" \
    --ops-file="$RELEASE_REPO/manifests/change-vcap-password.yml" \
    --ops-file="$RELEASE_REPO/manifests/add-go-syslogd.yml" \
    --ops-file="$RELEASE_REPO/manifests/add-syslog-migration.yml" \
    --ops-file="$RELEASE_REPO/manifests/add-embedded-tests.yml" \
    --vars-file="$RELEASE_REPO/manifests/lite-vars-file.yml" \
    --var=director-uuid="$bosh_uuid" \
  "$RELEASE_REPO/manifests/cf-rabbitmq-broker-template.yml" \
  > "$new_manifest"

  echo "$new_manifest"
}

main "$@"
