#!/usr/bin/env bash

set -e

main() {
  install_dependencies
  run_unit_tests
  run_service_broker_tests
}

install_dependencies() {
  bundle install
}

run_unit_tests() {
  bundle exec rake spec:unit
}

run_service_broker_tests() {
  pushd src/rabbitmq-service-broker
    make ci_tests
  popd
}

main
