#!/usr/bin/env bash

MY_DIR="$(dirname "$0")"

cd "${MY_DIR}/.." || exit

BOSH_MANIFEST=${BOSH_MANIFEST:-$(./scripts/interpolate-manifest-for-bosh-lite)}

bundle install
bundle exec rspec spec/system --fail-fast
